---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 10184.
--- DateTime: 2022/2/28 14:43
---
---@class FollowPlayerHelper
local FollowPlayerHelper = T(Global, "FollowPlayerHelper")

---@param follower CBasePlayer
function FollowPlayerHelper:onUpdate(follower, frameTime, renderDt)
    if not follower or not follower.Player or follower.Player.isDead then
        Blockman.Instance():setRenderViewEntity(PlayerManager:getClientPlayer().Player)
        return false
    end
    PlayerManager:getClientPlayer().Player:setActorInvisible(false)
    ---设置玩家坐标为跟随着坐
    local selfPlayer = PlayerManager:getClientPlayer().Player
    local position = VectorUtil.add3(follower:getPosition(renderDt), VectorUtil.newVector3(0, 1.62, 0))
    selfPlayer:setPosition(position)
    if not Blockman.Instance().m_gameSettings:isMouseMoving() then
        ---当玩家滑动屏幕时，摄像机不再随被跟随者转动，松手后摄像机转回被跟随者视角
        local yaw = follower:getYaw()
        local pitch = follower:getPitch()
        local yawDiff = math.fmod(yaw - selfPlayer.rotationYaw, 360)
        if yawDiff > 180 or yawDiff < -180 then
            yawDiff = -yawDiff
        end
        local pitchDiff = pitch - selfPlayer.rotationPitch
        local speed = 360
        ---设置yaw值
        if math.abs(yawDiff) < (frameTime / 1000) * speed then
            selfPlayer.rotationYaw = yaw
        else
            selfPlayer.rotationYaw = selfPlayer.rotationYaw + (yawDiff / math.abs(yawDiff)) * speed * (frameTime / 1000)
        end
        ---设置pitch值
        if math.abs(pitch - selfPlayer.rotationPitch) < (frameTime / 1000) * speed then
            selfPlayer.rotationPitch = pitch
        else
            selfPlayer.rotationPitch = selfPlayer.rotationPitch + (pitchDiff / math.abs(pitchDiff)) * speed * (frameTime / 1000)
        end
    end
    Blockman.Instance():setRenderViewEntity(follower.Player)
    return true
end